core/urls.py
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from .views import (HomeView,
ItemDetailView,
CheckoutView,
add_to_cart,
remove_from_cart,
OrderSummaryView,
remove_single_item_from_cart,
PaymentView,
AddCouponView,
RequestRefundView,
MyCustomSignupForm,
add_to_wishlist,
remove_from_wishlist,
WishlistSummaryView,
ShopAllView,
ShopView,
)
from django.views.generic import TemplateView

app_name = 'core'
#when a class based view is called use the as.view func
urlpatterns = [
    path('',HomeView.as_view(), name='home'),
    path('checkout/',CheckoutView.as_view(), name='checkout'),
    path('order-summary/',OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/',ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/',add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/',remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
         #here slug as payment_option which would select the payment option that was selected by the user
    path('payment/<payment_option>/',PaymentView.as_view(), name='payment'),
    path('request-refund/',RequestRefundView.as_view(), name='request-refund'),
    path ('signup/',MyCustomSignupForm.as_view(),name='signup'),
    path('wishlist-summary/',WishlistSummaryView.as_view(), name='wishlist-summary'),
    path('add_to_wishlist/<slug>/',add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<slug>/',remove_from_wishlist, name='remove_from_wishlist'),
    path('contact/', 
    TemplateView.as_view(template_name='contact.html'),
    name='contact'),
    path('shop-all/',ShopAllView.as_view(), name='shop-all'),
    path('shop/clothing/',ShopView.as_view(), name='clothing'),
    path('shop/clothing/shawls/',ShopView.as_view(), name='shawls'),
    path('shop/clothing/gowns/',ShopView.as_view(), name='gowns'),
    path('shop/clothing/scarfs/',ShopView.as_view(), name='scarfs'),
    path('shop/decor/',ShopView.as_view(), name='decor'),
    path('shop/foods/',ShopView.as_view(), name='foods'),
    path('shop/foods/saffron/',ShopView.as_view(), name='saffron'),
    path('shop/foods/honey/',ShopView.as_view(), name='honey'),
    path('shop/foods/tea/',ShopView.as_view(), name='tea'),
    path('shop/foods/dryfruits/',ShopView.as_view(), name='dryfruits'),
    
]
#purana kaam
if settings.DEBUG:
      import debug_toolbar
      urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
      urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
      urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('allauth.urls')),
    path('',include('core.urls',namespace='core'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/',include(debug_toolbar.urls))]
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
#for using our auth user model
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.db.models.signals import post_save

CATEGORY_CHOICES =(
    #'what goes in db' ,'what is displayed'
    ('S','Shawls'),
    ('G','Gowns'),
    ('SC','Scarfs'),
    ('D','Decor'),
    ('SF','Saffron'),
    ('H','Honey'),
    ('T','Tea'),
    ('DF','Dry-Fruits'),   
)

LABEL_CHOICES =(
    #'what goes in db' ,'what is displayed'
    ('p','primary'),
    ('S','secondary'),
    ('D','danger')
)

ADDRESS_CHOICES =(
    #'what goes in db' ,'what is displayed'
    ('B','Billing'),
    ('S','Shipping'),
  
)

''' 
LIFE CYCLE OF A ORDER IN ECOMMERCE
1. Item added to cart
2. Adding a billing address
(failed checkout)
3.Payment service
(preprocessing,processing,packaging)
4.Being Delievred/ready to deliver
5.Received
6.Refunds
'''

# Create your models here.

#can be used to store card info and maybe previous order info
class UserProfile(models.Model):
    #MAYBE FOR ORDER IT NEED TO BE ONE TO MANY
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    #this field would be filled if the user saves their info when they checkout
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False) # this is a whole concept which needs some work to done

    def __str__(self):
        return self.user.username

#inherits models class defined in django
#Model for the items we can purchase
#but when you add a item to the cart it becomes Orderitem
class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    #diff imgs for diff items
    image = models.ImageField()
    discount_price = models.FloatField(blank=True, null =True)
    category = models.CharField(choices=CATEGORY_CHOICES,max_length=2)
    label = models.CharField(blank=True, null =True,choices=LABEL_CHOICES,max_length=1)
    slug =models.SlugField()
    description = models.TextField()
   
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product",kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart",kwargs={
            'slug': self.slug
        })
    
    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart",kwargs={
            'slug': self.slug
        })

    def get_add_to_wishlist_url(self):
        return reverse("core:add_to_wishlist",kwargs={
            'slug': self.slug
        })
    
    
    def get_remove_from_wishlist_url(self):
        return reverse("core:remove_from_wishlist",kwargs={
            'slug': self.slug
        })
    
   
    



#this model is used to link between item model and the order model
class OrderItem(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    ordered =models.BooleanField(default=False)
    #for making a one to many relation between Item model and Orderitem model
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
     #default is one so that when a product is added to cart only one instance of that is added to cart
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
   
    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()
    
   

#model for shopping cart in which you add a product to order
class Order(models.Model):
    #for associating a order with a user
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    #reference code  is used for reffering to a order when asked for a refund
    ref_code = models.CharField(max_length=20,blank=True, null=True)
   #items for adding orderitems into order
    items = models.ManyToManyField(OrderItem)
   #for storing the time the order was *created*
    start_date =models.DateTimeField(auto_now_add=True)
   #storing manually here that value the moment that the item is ordered
    ordered_date = models.DateTimeField()
    #when a product is ordered
    ordered = models.BooleanField(default=False)

    billing_address = models.ForeignKey('Address',related_name='billing_address', on_delete=models.SET_NULL ,blank=True, null=True)
    #related name used as foreign key in both fields is on the same model
    shipping_address = models.ForeignKey('Address',related_name='shipping_address', on_delete=models.SET_NULL ,blank=True, null=True)
    #as we want to get the payment Model related to the order itself as we did with billing address
    payment = models.ForeignKey('Payment',on_delete=models.SET_NULL ,blank=True, null=True)

    #we want here to assign the coupon to the order
    coupon = models.ForeignKey('Coupon',on_delete=models.SET_NULL ,blank=True, null=True)

    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False) 
    refund_requested = models.BooleanField(default=False) ##imp field which needs some work
    refund_granted = models.BooleanField(default=False) 
   
    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        #subtract amount of coupon applied from total here
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
     user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

     street_address = models.CharField(max_length=100)
     house_address = models.CharField(max_length=100)
     country =CountryField(multiple=False)
     zip = models.CharField(max_length=100)
     address_type = models.CharField(max_length=1,choices=ADDRESS_CHOICES )#address type billing or shipping address
                                                                          #shipping address = where the order is to be delivered
                                                                         #billing address = where you live
    #default used in process of storing the address for further orders
     default=models.BooleanField(default=False)

     def __str__(self):
        return self.user.username
    
    #this is used to change the meta deta of a model
     class Meta:
         verbose_name_plural='Addresses'


#as we want to keep track of actual stripe payment thus we create a class for it
class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    #if the user is deleted we dont want the payment to be deleted as we want to keep track of every payment
    #thus we keep the user field on_delete as null
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.SET_NULL, blank=True ,null =True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code =models.CharField(max_length=15)
    #amount that is to subtracted from total when coupon is applied
    amount = models.FloatField()

    def __str__(self):
        return self.code

#to store the refund for our own use
class Refund(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    #reason for refunding the order
    reason = models.TextField()
    #if refund accepted or not
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        #pk=primary key
        return f"{self.pk}"



def userprofile_receiver(sender,instance,created, *args, **kwargs):
    #this checks if the user is created which is basically in the sender argument
    if created:
        userprofile = UserProfile.objects.create(user=instance)


#we are using this post save signal to create the USER-PROFILE the moment that user is created
#inshort jab naya USER banega tab hi uska USER PROFILE  b banega using the logic in above func and below post
post_save.connect(userprofile_receiver,sender=settings.AUTH_USER_MODEL)



class WishlistItem(models.Model):


    already_added=models.BooleanField(default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)# here CASCADE is the behavior to adopt when the referenced object(because it is a foreign key) is deleted. it is not specific to django,this is an sql standard.
    item = models.ForeignKey(Item,on_delete =models.CASCADE)
  

    def __str__(self):
        return f"{self.item.title}"
   
    def get_total_item_price(self):
        return self.item.price

    def get_total_discount_item_price(self):
        return self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Wishlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    items = models.ManyToManyField(WishlistItem)

    already_added = models.BooleanField(default=False)
    date_created = models.DateTimeField()

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()

templates/footer.html
<!--used for loading the cart count logic here in navbar-->
{% load cart_template_tags %}
<!-- Footer Section Begin -->
{% load static %}
<footer class="footer">
  <hr />
  <br />
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-6 col-sm-7">
        <div class="footer__about">
          <div class="footer__logo mb-0">
            <a href="{% url 'core:home' %}"
              ><span
                style="
                  font-family: 'Butterfly Kids', cursive;
                  color: black;
                  font-size: 50px;
                "
                >Yander</span
              ></a
            >
          </div>
          <p>
            Online shopping for exquisite Kashmir Art and Craft made easy at
            Yander.<br /><br />
            "A brand is a voice, and a product is a souvenir."
          </p>
          <div class="footer__payment">
            <a href="#"
              ><img src="{% static 'core/img/payment/payment-1.png' %}" alt=""
            /></a>
            <a href="#"
              ><img src="{% static 'core/img/payment/payment-2.png' %}" alt=""
            /></a>
            <a href="#"
              ><img src="{% static 'core/img/payment/payment-3.png' %}" alt=""
            /></a>
            <a href="#"
              ><img src="{% static 'core/img/payment/payment-4.png' %}" alt=""
            /></a>
            <a href="#"
              ><img src="{% static 'core/img/payment/payment-5.png' %}" alt=""
            /></a>
          </div>
        </div>
      </div>
      <div class="col-lg-2 col-md-3 col-sm-5">
        <div class="footer__widget">
          <h6>Quick links</h6>
          <ul>
            <li><a href="{% url 'core:home' %}">Home</a></li>
            <li><a href="shop-all">Shop All</a></li>
            <li><a href="{% url 'core:clothing' %}">Clothing</a></li>
            <li><a href="{% url 'core:decor' %}">Decor</a></li>
            <li><a href="{% url 'core:foods' %}">Organic Foods</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-2 col-md-3 col-sm-4">
        <div class="footer__widget">
          <h6>Account</h6>
          <ul>
            <!-- <li><a href="#">My Account</a></li> -->
            <!-- <li><a href="#">Orders</a></li> -->
            <li><a href="{% url 'core:order-summary' %}">Checkout</a></li>
            <li><a href="{% url 'core:wishlist-summary' %}">Wishlist</a></li>
            <li><a href="{% url 'core:contact' %}">Contact Us</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-4 col-md-8 col-sm-8">
        <div class="footer__newslatter">
          <h6>NEWSLETTER</h6>
          <form action="#">
            <input type="text" placeholder="Email" />
            <button type="submit" class="site-btn">Subscribe</button>
          </form>
          <div class="footer__social text-center">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-youtube-play"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
            <a href="#"><i class="fa fa-pinterest"></i></a>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="footer__copyright__text">
          <p>
            Copyright &copy;
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved | This Website is made with
            <i class="fa fa-heart" aria-hidden="true"></i> by
            <a href="https://instagram.com/foxdie.offical" target="_blank"
              >FOXDIE&trade;</a
            >
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- Footer Section End -->

templates/navbar.html
<!--used for loading the cart count logic here in navbar-->
{% load cart_template_tags %}

<!-- Page Preloder -->
<div id="preloder">
  <div class="loader"></div>
</div>

<!-- Offcanvas Menu Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
  <div class="offcanvas__close">+</div>
  <ul class="offcanvas__widget" style="margin-right: 23px; text-align: left;">
    <!-- <li><span class="icon_search search-switch    "></span></li> -->
    {% if request.user.is_authenticated %}
    <div class="header__right__auth mr-4 pr-2">
      <a ><strong>{{ request.user }}</strong></a>
    </div>
    <li>
      <a href="{% url 'core:wishlist-summary' %}"
        ><span class="icon_heart_alt"></span>
        <!-- <div class="tip"><span></span></div> -->
      </a>
    </li>
    <li>
      <a href="{% url 'core:order-summary' %}"> 
        <span class="icon_bag_alt"></span>
        <div class="tip"><span>{{request.user|cart_item_count}}</span></div>
      </a>
    </li> 
    
    {% endif %}
  </ul>
  <div class="offcanvas__logo">
    <a href="{% url 'core:home' %}"
      ><span
        style="
          font-family: 'Butterfly Kids', cursive;
          color: black;
          font-size: 50px;
        "
        >Yander</span
      ></a
    >
  </div>
  <div id="mobile-menu-wrap"></div>
  <div class="offcanvas__auth">
    {% if request.user.is_authenticated %}
    <a href="{% url 'account_logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'account_login' %}">Login</a>
    <a href="{% url 'account_signup' %}">Register</a>
    {% endif %}
  </div>
</div>
<!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
<header class="header">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xl-3 col-lg-2">
        <div class="header__logo p-0 mt-2 pl-1">
          <a href="{% url 'core:home' %}"
            ><span
              style="
                font-family: 'Butterfly Kids', cursive;
                color: black;
                font-size: 50px;
              "
              >Yander</span
            ></a
          >
        </div>
      </div>
      <div class="col-xl-6 col-lg-7">
        <nav class="header__menu">
          <ul>
            <li {% if request.path == "/" %} class="active" {% endif %}><a href="{% url 'core:home' %}">Home</a></li>
            <li {% if request.path == "/shop-all/" %} class="active" {% endif %}><a href="{% url 'core:shop-all' %}">Shop</a></li>
            <li {% if request.path == "/shop/clothing/" or request.path == "/shop/clothing/shawls/" or request.path == "/shop/clothing/gowns/" or request.path == "/shop/clothing/scarfs/" %} class="active" {% endif %}><a href="{% url 'core:clothing' %}">Clothing</a>
              <ul class="dropdown">
                <li>
                  <a href="{% url 'core:shawls' %}">Shawls</a>
                </li>
                <li><a href="{% url 'core:gowns' %}">Gowns</a></li>
                <li><a href="{% url 'core:scarfs' %}">Scarfs</a></li>
              </ul></li>
              <li {% if request.path == "/shop/decor/" %} class="active" {% endif %}><a href="{% url 'core:decor' %}">Decor</a></li>
            <li {% if request.path == "/shop/foods/" or request.path == "/shop/foods/saffron/" or request.path == "/shop/foods/honey/" or request.path == "/shop/foods/tea/" or request.path == "/shop/foods/dryfruits/" %} class="active" {% endif %}>
              <a href="{% url 'core:foods' %}">Organic Foods</a>
              <ul class="dropdown">
                <li>
                  <a href="{% url 'core:saffron' %}">Saffron</a>
                </li>
                <li><a href="{% url 'core:dryfruits' %}">Dry Fruits</a></li>
                <li><a href="{% url 'core:honey' %}">Organic Honey</a></li>
                <li><a href="{% url 'core:tea' %}">Organic Tea</a></li>
              </ul>
            </li>
            
            <li {% if request.path == "/contact/" %} class="active" {% endif %}><a href="{% url 'core:contact' %}">Contact</a></li>
          </ul>
        </nav>
      </div>
      <div class="col-lg-3">
        <div class="header__right">
          {% if request.user.is_authenticated %}
         
          <ul class="header__right__widget">
            <!-- <li><span class="icon_search search-switch"></span></li> -->
            <li>
              <a href="{% url 'core:wishlist-summary' %}"
                ><span class="icon_heart_alt"></span>
                <!-- <div class="tip"></div> -->
              </a>
            </li>
            <li>
              <a href="{% url 'core:order-summary' %}"
               class= ><span class="icon_bag_alt"></span>
                <div class="tip">{% if request.user|cart_item_count == None %}<span>0</span>{% else %}<span>{{request.user|cart_item_count}}</span>{% endif %}</div>
              </a>
            </li>
            
          </ul>
          <div class="header__right__auth pl-4 mr-0 ml-3">
            <a><strong>{{ request.user }}</strong></a>
          </div>
          <div class="header__right__auth pl-4">
            <a href="{% url 'account_logout' %}">Logout</a>
          </div>
          
          {% else %}
          <div class="header__right__auth">
            <a href="{% url 'account_login' %}">Login</a>
            <a href="{% url 'account_signup' %}">Register</a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="canvas__open">
      <i class="fa fa-bars"></i>
    </div>
  </div>
</header>
<!-- Header Section End -->

templates/order_summary.html
{% extends "base.html" %} {% block content %}

<!-- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------->

<!-- Breadcrumb Begin -->
<div class="breadcrumb-option">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb__links">
          <a href="{% url 'core:home' %}"><i class="fa fa-home"></i> Home</a>
          <span>Shopping Cart</span>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Breadcrumb End -->

<!-- Heading -->
<h2 class="my-5 h2 text-center"><b>Order Summary</b></h2>

<!-- Shop Cart Section Begin -->
<section class="shop-cart spad">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="shop__cart__table">
          <table>
            <thead>
              <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <!--as here items is the field of Order Model which has manytomany relation with Orderitem model -->
              <!--all is used here bcoz there is manytomany relation btwn orderitem and order model-->
              {% for order_item in object.items.all %}
              <tr>
                <!--for loop variable accesing the field of OrderItem models namely item which has a relation with Item Model 
                 which has the Title field-->
                <td class="cart__product__item">
                  <a href="{{ order_item.item.get_absolute_url }}">
                    <img
                      src="{{ order_item.item.image.url }}"
                      alt=""
                      style="width: 60px;"
                  /></a>
                  <!-- <img src="img/shop-cart/cp-1.jpg" alt="" /> -->
                  <div class="cart__product__item__title">
                    <a href="{{ order_item.item.get_absolute_url }}">
                      <h6>{{ order_item.item.title }}</h6></a
                    >
                    <div class="rating">
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                    </div>
                  </div>
                </td>
                <td class="cart__price">&#x20B9;{{order_item.item.price}}</td>
                <td class="cart__quantity">
                  <a
                    href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"
                    style="text-decoration: none; color: inherit;"
                    ><i class="fa fa-minus ml-2"></i
                  ></a>
                  <span class="p-lg-4 p-md-4 p-sm-4"
                    >{{order_item.quantity}}</span
                  >
                  <a
                    href="{% url 'core:add-to-cart' order_item.item.slug %}"
                    style="text-decoration: none; color: inherit;"
                    ><i class="fa fa-plus"> </i
                  ></a>
                </td>
                <td class="cart__total">
                  {% if order_item.item.discount_price %} &#x20B9;<span
                    >{{ order_item.get_total_discount_item_price }}</span
                  >
                  <span class="badge badge-success p-1"
                    >saved &#x20B9;{{ order_item.get_amount_saved }}</span
                  >
                  {% else %} &#x20B9;
                  <span>{{ order_item.get_total_item_price }}</span>{% endif %}
                </td>
                <td class="cart__close">
                  <a
                    href="{% url 'core:remove-from-cart' order_item.item.slug %}"
                  >
                    <span class="icon_close"></span
                  ></a>
                </td>
              </tr>
              <!-- --------------------------------->
              <!--for coupon code row-->
              {% if object.coupon %} {% if forloop.last %}
              <tr>
                <td colspan="3"><b>Coupon Discount</b></td>
                <td><b> -&#x20B9;{{ object.coupon.amount }}</b></td>
              </tr>
              {% endif %} {% endif %}
              <!--coupon end-->
              <!--for if cart is empty-->
              {% empty %}
              <tr>
                <td colspan="5 " class="text-center">
                  It seems your cart is empty, lets fill it up with some
                  happiness :)
                </td>
              </tr>

              <!--empty end-->
              {% endfor %}

              <!-- <tr>
                <td class="cart__product__item">
                  <img src="img/shop-cart/cp-2.jpg" alt="" />
                  <div class="cart__product__item__title">
                    <h6>Zip-pockets pebbled tote briefcase</h6>
                    <div class="rating">
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                    </div>
                  </div>
                </td>
                <td class="cart__price">$ 170.0</td>
                <td class="cart__quantity">
                  <div class="pro-qty">
                    <input type="text" value="1" />
                  </div>
                </td>
                <td class="cart__total">$ 170.0</td>
                <td class="cart__close">
                  <span class="icon_close"></span>
                </td>
              </tr>
              <tr>
                <td class="cart__product__item">
                  <img src="img/shop-cart/cp-3.jpg" alt="" />
                  <div class="cart__product__item__title">
                    <h6>Black jean</h6>
                    <div class="rating">
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                    </div>
                  </div>
                </td>
                <td class="cart__price">$ 85.0</td>
                <td class="cart__quantity">
                  <div class="pro-qty">
                    <input type="text" value="1" />
                  </div>
                </td>
                <td class="cart__total">$ 170.0</td>
                <td class="cart__close">
                  <span class="icon_close"></span>
                </td>
              </tr>
              <tr>
                <td class="cart__product__item">
                  <img src="img/shop-cart/cp-4.jpg" alt="" />
                  <div class="cart__product__item__title">
                    <h6>Cotton Shirt</h6>
                    <div class="rating">
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                    </div>
                  </div>
                </td>
                <td class="cart__price">$ 55.0</td>
                <td class="cart__quantity">
                  <div class="pro-qty">
                    <input type="text" value="1" />
                  </div>
                </td>
                <td class="cart__total">$ 110.0</td>
                <td class="cart__close">
                  <span class="icon_close"></span>
                </td>
              </tr> -->
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-6">
        <div class="cart__btn">
          <a href="{% url 'core:home' %}">Continue Shopping</a>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6">
        {% if object.get_total %}
        <div class="cart__total__procced">
          <h6>Cart total</h6>
          <ul>
            <li>Subtotal <span>&#x20B9;{{object.get_total}}</span></li>
            <li>Total <span>&#x20B9;{{object.get_total}}</span></li>
          </ul>
          <a
            href="/checkout/"
            class="btn btn-secondary btn-lg btn-block site-btn"
            >Proceed to checkout</a
          >
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</section>
<!-- Shop Cart Section End -->

{% endblock content %}